server:
  port: 8019
  tomcat:
    max-http-form-post-size: 10000MB
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    # 连接redis数据源的索引
    database: 1
    # 超时毫秒数
    timeout: 5000
    jedis:
      pool:
        # 连接池最大连接数
        max-active: 15
        # 最大空闲连接数
        max-idle: 8
        # 最小空间连接数
        min-idle: 0
        # 连接池最大阻塞等待时间
        max-wait: 5000
  cache:
    type: redis
    redis:
      #10小时定时删除
      time-to-live: 36000
      # 缓存数据key是否使用前缀
      use-key-prefix: true
      # 是否缓存null数据
      cache-null-values: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/auth_db?useUnicode=true&characterEncodeing=UTF-8&useSSL=false&serverTimezone=GMT
    username: root
    password: yzy20021009
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
  type-aliases-package: com.cache.pojo