spring:
  mail:
    host: smtp.163.com
    username: yzy1565115013@163.com
    password: EENGVQYLQNYAXXHI
    port: 994
    protocol: smtps
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
          debug: true
server:
  port: 8020